### PR TITLE
Fix tick labels

### LINKED ISSUE #25: tick text needs to be raised when the axis is top & text is more than a line
currently, if the tick text is two or more lines, the second & beyond lines are behind the line of the axis and the chart

### PR DESCRIPTION
**Pull request by kstrack-grose**
corrects placement for multi-line tick labels when the axis is orientated top
@boygirl 

resolves #25

### CODE REVIEW

File: src/components/victory-axis.jsx [hunk 1]
```diff
@@ -437,11 +439,14 @@ class VAxis extends React.Component {
...
     const textLines = textString.split("\n");
-    return _.map(textLines, (line, index) => {
+    const HTMLtextLines = _.map(textLines, (line, index) => {
       return index === 0 ?
       (<tspan x={x} key={"text-line-" + index}>{line}</tspan>) :
       (<tspan x={x} dy="1.2em" key={"text-line-" + index}>{line}</tspan>);
     });
+    const heightOfLines = this.props.orientation === "top" ?
+     (textLines.length - 1) * this.style.tickLabels.fontSize * 1.25 : 0;
+    return [heightOfLines, HTMLtextLines];
```
Comment (boygirl) [inline src/components/victory-axis.jsx]: please return `heightOfLines` from a separate function rather than returning it in an array here

File: src/components/victory-axis.jsx [hunk 2]
```diff
@@ -392,11 +394,11 @@ class VAxis extends React.Component {
             y2={this.tickProperties.y2}
             style={this.style.ticks}/>
           <text x={this.tickProperties.x}
-            y={this.tickProperties.y}
+            y={(this.tickProperties.y - textLengthAndLines[0])}
```
Comment (boygirl) [inline src/components/victory-axis.jsx]: get this value from a new function. If you must return several things from a function, use an object with meaningful keys

**Comment by boygirl** [comment]
@kstrack-grose It works well. Approved pending breaking line height stuff out into a new function `getLineHeight` or something.  Also, please run `npm run check` and pass CI

**Comment by kstrack-grose** [comment]
@boygirl That makes a lot of sense! I'll get a new commit in.

File: src/components/victory-axis.jsx [hunk 3]
```diff
@@ -457,7 +470,7 @@ class VAxis extends React.Component {
           x={x}
           style={this.style.axisLabels}
           transform={this.isVertical ? "rotate(-90)" : ""}>
-          {this.getTextLines(this.props.label, x)}
+          {this.getTextLines(this.props.label, x)[1]}
```
Comment (exogen) [inline src/components/victory-axis.jsx]: I think this `[1]` is vestigial from when it was returning a 2-array?
